//! Conversion engine using Alien and fpm wrapped inside a bubblewrap (`bwrap`) sandbox.

use std::path::{Path, PathBuf};
use std::process::Stdio;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::{Duration, Instant};

use super::detect::PkgFormat;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TargetFmt {
    Deb,
    Rpm,
    Pacman,
}

impl TargetFmt {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Deb => "deb",
            Self::Rpm => "rpm",
            Self::Pacman => "pacman",
        }
    }

    pub fn ext(&self) -> &'static str {
        match self {
            Self::Deb => ".deb",
            Self::Rpm => ".rpm",
            Self::Pacman => ".pkg.tar.zst",
        }
    }

    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "deb" => Some(Self::Deb),
            "rpm" => Some(Self::Rpm),
            "pacman" | "pkg.tar.zst" => Some(Self::Pacman),
            _ => None,
        }
    }
}

pub struct ConvertResult {
    pub output_path: PathBuf,
    #[allow(dead_code)]
    pub output_filename: String,
    #[allow(dead_code)]
    pub wall_secs: f64,
    pub deps_warning: Option<String>,
}

#[derive(Debug, thiserror::Error)]
pub enum ConvertError {
    #[error("Timeout during conversion")]
    Timeout,
    #[error("Failed to spawn sandbox process: {0}")]
    SpawnFailed(String),
    #[error("Process failed with exit code {exit_code}: {stderr}")]
    ProcessFailed { exit_code: i32, stderr: String },
    #[error("No output file generated by converter")]
    NoOutput,
    #[error("Cancelled by user")]
    Cancelled,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConversionTool {
    Alien,
    Fpm,
}

pub fn select_tool(src: PkgFormat, dst: TargetFmt) -> ConversionTool {
    match (src, dst) {
        (PkgFormat::Deb, TargetFmt::Rpm) | (PkgFormat::Rpm, TargetFmt::Deb) => {
            ConversionTool::Alien
        }
        _ => ConversionTool::Fpm,
    }
}

pub fn build_tool_cmd(src: PkgFormat, dst: TargetFmt, input_name: &str) -> (String, Vec<String>) {
    match select_tool(src, dst) {
        ConversionTool::Alien => {
            let flag = match dst {
                TargetFmt::Rpm => "--to-rpm",
                TargetFmt::Deb => "--to-deb",
                TargetFmt::Pacman => "--to-pkg", // Alien doesn't do pacman; fallback fpm handles pacman
            };
            let bin = if Path::new("/usr/bin/alien").exists() {
                "/usr/bin/alien"
            } else {
                "alien"
            };
            (
                bin.to_string(),
                vec![
                    flag.to_string(),
                    "--scripts".to_string(),
                    input_name.to_string(),
                ],
            )
        }
        ConversionTool::Fpm => {
            let src_str = match src {
                PkgFormat::Deb => "deb",
                PkgFormat::Rpm => "rpm",
                PkgFormat::Pacman => "pacman",
            };
            let dst_str = match dst {
                TargetFmt::Deb => "deb",
                TargetFmt::Rpm => "rpm",
                TargetFmt::Pacman => "pacman",
            };
            let bin = if Path::new("/usr/local/bin/fpm").exists() {
                "/usr/local/bin/fpm"
            } else if Path::new("/usr/bin/fpm").exists() {
                "/usr/bin/fpm"
            } else {
                "fpm"
            };
            (
                bin.to_string(),
                vec![
                    "-s".to_string(),
                    src_str.to_string(),
                    "-t".to_string(),
                    dst_str.to_string(),
                    input_name.to_string(),
                ],
            )
        }
    }
}

/// Spawns the sandbox process with bwrap.
pub fn spawn_bwrap(
    work_dir: &Path,
    input_name: &str,
    src: PkgFormat,
    dst: TargetFmt,
) -> std::io::Result<std::process::Child> {
    let (tool_bin, tool_args) = build_tool_cmd(src, dst, input_name);

    let work_dir_str = work_dir.to_string_lossy().to_string();

    let mut bwrap_args = vec![
        "--unshare-all".to_string(),
        "--unshare-user".to_string(),
        "--unshare-pid".to_string(),
        "--uid".to_string(),
        "65534".to_string(),
        "--gid".to_string(),
        "65534".to_string(),
        "--setenv".to_string(),
        "PATH".to_string(),
        "/usr/local/bin:/usr/bin:/bin".to_string(),
        "--setenv".to_string(),
        "SHELL".to_string(),
        "/bin/bash".to_string(),
        "--setenv".to_string(),
        "HOME".to_string(),
        "/tmp".to_string(),
        "--setenv".to_string(),
        "LANG".to_string(),
        "C.UTF-8".to_string(),
        "--ro-bind".to_string(),
        "/usr".to_string(),
        "/usr".to_string(),
    ];

    if Path::new("/bin").exists() {
        bwrap_args.push("--ro-bind".to_string());
        bwrap_args.push("/bin".to_string());
        bwrap_args.push("/bin".to_string());
    }
    if Path::new("/lib").exists() {
        bwrap_args.push("--ro-bind".to_string());
        bwrap_args.push("/lib".to_string());
        bwrap_args.push("/lib".to_string());
    }
    if Path::new("/lib64").exists() {
        bwrap_args.push("--ro-bind".to_string());
        bwrap_args.push("/lib64".to_string());
        bwrap_args.push("/lib64".to_string());
    }
    if Path::new("/var").exists() {
        bwrap_args.push("--ro-bind".to_string());
        bwrap_args.push("/var".to_string());
        bwrap_args.push("/var".to_string());
    }
    bwrap_args.push("--tmpfs".to_string());
    bwrap_args.push("/var/tmp".to_string());

    if Path::new("/etc").exists() {
        bwrap_args.push("--ro-bind".to_string());
        bwrap_args.push("/etc".to_string());
        bwrap_args.push("/etc".to_string());
    }

    bwrap_args.extend(vec![
        "--proc".to_string(),
        "/proc".to_string(),
        "--dev".to_string(),
        "/dev".to_string(),
        "--tmpfs".to_string(),
        "/tmp".to_string(),
        "--bind".to_string(),
        work_dir_str.clone(),
        "/work".to_string(),
        "--chdir".to_string(),
        "/work".to_string(),
        "--die-with-parent".to_string(),
        "--new-session".to_string(),
    ]);

    bwrap_args.push("--".to_string());
    bwrap_args.push(tool_bin);
    bwrap_args.extend(tool_args);

    std::process::Command::new("/usr/bin/bwrap")
        .args(&bwrap_args)
        .current_dir(work_dir)
        .stdout(Stdio::null())
        .stderr(Stdio::piped())
        .spawn()
}

/// Synchronous conversion runner designed for `spawn_blocking`.
pub fn run_convert_sync(
    work_dir: &Path,
    input_path: &Path,
    src: PkgFormat,
    dst: TargetFmt,
    timeout: Duration,
    trace_id: u64,
    cancel: &Arc<AtomicBool>,
) -> Result<ConvertResult, ConvertError> {
    let input_name = input_path
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_default();

    log_ev!("pkgconvert", trace_id, "convert_start", "src" => src.as_str(), "dst" => dst.as_str());

    let mut child = match spawn_bwrap(work_dir, &input_name, src, dst) {
        Ok(c) => c,
        Err(e) => {
            // Fallback: if bwrap fails to spawn (e.g., in minimal dev environment without bwrap),
            // log event and attempt direct execution if bwrap is missing
            log_ev!("pkgconvert", trace_id, "bwrap_fallback", "err" => format!("{e}"));
            let (cmd, args) = build_tool_cmd(src, dst, &input_name);
            std::process::Command::new(&cmd)
                .args(&args)
                .current_dir(work_dir)
                .stdout(Stdio::null())
                .stderr(Stdio::piped())
                .spawn()
                .map_err(|err| ConvertError::SpawnFailed(err.to_string()))?
        }
    };

    // Actively drain stderr in a background thread to prevent pipe deadlock on >64KB output
    let stderr_thread = child.stderr.take().map(|mut pipe| {
        std::thread::spawn(move || {
            let mut buf = Vec::new();
            use std::io::Read;
            let _ = pipe.read_to_end(&mut buf);
            buf
        })
    });

    let t0 = Instant::now();
    let status_res = loop {
        match child.try_wait() {
            Ok(Some(status)) => break Ok(status),
            Ok(None) => {
                if cancel.load(Ordering::Relaxed) {
                    let _ = child.kill();
                    let _ = child.wait();
                    if let Some(handle) = stderr_thread {
                        let _ = handle.join();
                    }
                    log_ev!("pkgconvert", trace_id, "convert_killed", "reason" => "cancelled");
                    return Err(ConvertError::Cancelled);
                }
                if t0.elapsed() >= timeout {
                    let _ = child.kill();
                    let _ = child.wait();
                    if let Some(handle) = stderr_thread {
                        let _ = handle.join();
                    }
                    log_ev!("pkgconvert", trace_id, "convert_killed", "reason" => "timeout");
                    return Err(ConvertError::Timeout);
                }
                std::thread::sleep(Duration::from_millis(200));
            }
            Err(e) => {
                if let Some(handle) = stderr_thread {
                    let _ = handle.join();
                }
                return Err(ConvertError::ProcessFailed {
                    exit_code: -1,
                    stderr: e.to_string(),
                });
            }
        }
    };

    let status = status_res?;
    let stderr_bytes = stderr_thread
        .and_then(|handle| handle.join().ok())
        .unwrap_or_default();

    let stderr = String::from_utf8_lossy(&stderr_bytes).to_string();
    let wall_secs = t0.elapsed().as_secs_f64();

    log_ev!(
        "pkgconvert",
        trace_id,
        "convert_done",
        "exit_code" => status.code().unwrap_or(-1),
        "wall_secs" => format!("{wall_secs:.2}")
    );

    if !status.success() {
        return Err(ConvertError::ProcessFailed {
            exit_code: status.code().unwrap_or(-1),
            stderr,
        });
    }

    // Locate generated file in work_dir matching dst.ext()
    let mut output_file = None;
    let target_ext = dst.ext();

    if let Ok(entries) = std::fs::read_dir(work_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_file() {
                let name = path.file_name().unwrap_or_default().to_string_lossy();
                if name != input_name && name.ends_with(target_ext) {
                    output_file = Some((path.clone(), name.to_string()));
                    break;
                }
            }
        }
    }

    let (output_path, output_filename) = output_file.ok_or(ConvertError::NoOutput)?;

    if dst == TargetFmt::Pacman {
        if let Err(e) = super::pacman_fix::fix_pacman_pkginfo(&output_path) {
            log_ev!("pkgconvert", trace_id, "pacman_fix_warn", "err" => format!("{e}"));
        } else {
            log_ev!("pkgconvert", trace_id, "pacman_fix_ok", "file" => output_filename.as_str());
        }
    }

    // Scan stderr for dependency warnings
    let mut deps_warning = None;
    for line in stderr.lines() {
        if line.contains("warning:") || line.contains("dependency") || line.contains("unresolved") {
            deps_warning = Some(line.trim().to_string());
            break;
        }
    }

    Ok(ConvertResult {
        output_path,
        output_filename,
        wall_secs,
        deps_warning,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_select_tool() {
        assert_eq!(
            select_tool(PkgFormat::Deb, TargetFmt::Rpm),
            ConversionTool::Alien
        );
        assert_eq!(
            select_tool(PkgFormat::Rpm, TargetFmt::Deb),
            ConversionTool::Alien
        );
        assert_eq!(
            select_tool(PkgFormat::Deb, TargetFmt::Pacman),
            ConversionTool::Fpm
        );
        assert_eq!(
            select_tool(PkgFormat::Pacman, TargetFmt::Deb),
            ConversionTool::Fpm
        );
    }

    #[test]
    fn test_large_stderr_drain_no_deadlock() {
        // Linux default pipe buffer is 64KB (65536 bytes).
        // Writing 128KB to stderr without active draining causes child to deadlock.
        let mut child = std::process::Command::new("sh")
            .args(["-c", "head -c 131072 /dev/zero | tr '\\0' 'E' >&2; exit 1"])
            .stdout(Stdio::null())
            .stderr(Stdio::piped())
            .spawn()
            .expect("spawn sh");

        let stderr_thread = child.stderr.take().map(|mut pipe| {
            std::thread::spawn(move || {
                let mut buf = Vec::new();
                use std::io::Read;
                let _ = pipe.read_to_end(&mut buf);
                buf
            })
        });

        let t0 = Instant::now();
        let timeout = Duration::from_secs(5);
        let status = loop {
            match child.try_wait() {
                Ok(Some(status)) => break status,
                Ok(None) => {
                    if t0.elapsed() >= timeout {
                        let _ = child.kill();
                        let _ = child.wait();
                        panic!("Child process deadlocked on piped stderr >64KB!");
                    }
                    std::thread::sleep(Duration::from_millis(50));
                }
                Err(e) => panic!("try_wait failed: {e}"),
            }
        };

        let stderr_bytes = stderr_thread
            .and_then(|handle| handle.join().ok())
            .unwrap_or_default();

        assert!(!status.success());
        assert_eq!(stderr_bytes.len(), 131072);
        assert_eq!(stderr_bytes[0], b'E');
        assert_eq!(stderr_bytes[131071], b'E');
    }
}
